### ISSUE TITLE
Add brief information about labels/colors used by the bots

### ISSUE THREAD

**Issue by willingc** [python/devguide#418] opened 2018-09-18 20:14 UTC
From the Zulip chat:

> Ah, I didn't notice that awaiting review and awaiting merge are different states -- they have the same color. :-( It would be nice if all this was written up in the devguide, or at least the devguide had a pointer to some comment in bedevere's source where it's explained.

Write up info about labels and colors for the amazing @Mariatta's bots.

**Comment by Mariatta** [comment] 2018-09-18 20:14
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/python/core-workflow/issues/32 (Add the mention bot?), https://github.com/python/miss-islington/issues/43 (Add info about how to customize and use this bot for other repositories?), https://github.com/python/core-workflow/issues/239 (Bot for Github labels), https://github.com/python/devguide/issues/396 (Add a few missing in-use directives), and https://github.com/python/devguide/issues/296 (Add a section to explain the different GitHub PR labels).

**Comment by Mariatta** [comment] 2018-10-12 17:57
The auto labeling by bedevere was actually @brettcannon's work :) so I don't want to take any credit here.

I think it is duplicate of https://github.com/python/devguide/issues/296 though, or similar.

**Comment by brettcannon** [comment] 2018-10-19 19:11
I agree that this is a duplicate of #296 .

**Closed by brettcannon** 2018-10-19 19:11 UTC
