### ISSUE TITLE
Floating << in mobile

### ISSUE THREAD

**Issue by mariehuynh** [python/devguide#372] opened 2018-05-16 09:17 UTC
Shifts around when resizing and scrolling.

**Comment by brettcannon** [comment] 2018-05-16 16:28
Can you share a screenshot?

**Comment by mariehuynh** [comment] 2018-05-16 16:41
https://photos.app.goo.gl/Mab6VutMdXUTH8Ug2

**Comment by brettcannon** [comment] 2018-05-16 18:08
Looks like a French-style quote.

**Comment by willingc** [comment] 2018-05-17 13:57
Hi @mariehuynh, This looks like the sidebar open/close is not rendering properly on Android. I don't see the same behavior on Safari or Chrome when sized to mobile width.

**Comment by mariehuynh** [comment] 2018-05-30 02:07
I don't see any CSS in this repo that affects this, and traced the problem back to the default CSS in Sphinx.  We can override it via something like 

div#sidebarbutton span {
    position: sticky;
}

in tools/static/custom.css

**Comment by willingc** [comment] 2018-06-11 01:43
Thanks for the research @mariehuynh. I'm glad you were able to reproduce. Your suggestion seems like it will work. We may also see if the fix should be contributed back to the Sphinx project.

**Comment by mariehuynh** [comment] 2018-06-11 02:46
I can make the change and run some tests.  Can you point me at your protocol for testing before submission?

**Comment by ezio-melotti** [comment] 2018-09-11 17:17
I think it's best to fix this upstream on Sphinx.  Once the patch has been tested and accepted upstream we can either apply it here directly, or wait for the next Sphinx release.
We also don't have a specific list of supported browsers (other than "the main ones"), but Sphinx might.

**Comment by hugovk** [comment] 2022-12-23 08:42
> [photos.app.goo.gl/Mab6VutMdXUTH8Ug2](https://photos.app.goo.gl/Mab6VutMdXUTH8Ug2)

Adding that here for future reference:

<img src=https://user-images.githubusercontent.com/1324225/209302465-cfc890f7-289d-4e46-9060-6787d05f8b4e.png width=50%>

I've not seen this since we moved to Furo (https://github.com/python/devguide/pull/679), let's close this unless someone can still reproduce.

**Closed by hugovk** 2022-12-23 08:42 UTC
Labels: bug
