### ISSUE TITLE
Adding FAQ or "Do's and Don'ts" type section

### ISSUE THREAD

**Issue by csabella** [python/devguide#182] opened 2017-04-27 23:47 UTC
I'm new to contributing and, as such, I don't always know when something has been discussed before or if there's a reason for something being the way it is.  If the devguide had a FAQ or 'open discussions' section or 'decisions made' section, then it would be a helpful resource.

For example, some documentation pages follow PEP-8 and PEP-257 (thanks, Terry) of using an active verb, but other pages don't.  I didn't know if it was better to follow the style of the page or to use an active verb when adding a description.

Another example is that I opened a ticket for the copyright date because I didn't find the existing discussion.  I knew it was probably out there, but then I wasn't sure since I couldn't find it.  If there was a page to open discussions or decisions that have been made in the past, it might save core developers from having to rehash the same information.

Also, the churn open issue on this page might be something to add to an FAQ.

I'm sure you can come up with a lot more of these types of scenarios.

**Comment by brettcannon** [comment] 2017-04-28 00:28
The problem is that "you can come up with a lot more of these types of scenarios" 😉 . They are essentially endless, which is why we try to document everything once in a doc that thematically collects everything in one page. Otherwise we would end up with a FAQ full of odds-and-ends that don't get updated and is never quite good enough (we used to have a FAQ and we deleted it a couple of months ago for these very reasons).

So thanks for the idea, but I'm closing this in preference of updating the appropriate devguide pages rather than maintaining an FAQ.

**Closed by brettcannon** 2017-04-28 00:28 UTC

**Comment by csabella** [comment] 2017-04-28 00:50
Makes sense, thanks.  :-)

Is there a place in the devguide that mentions the preference for updating the action verbs on docs?  For example, the sqlite3 mixes styles, so when I made a change, I wasn't quite sure what to do.

**Comment by brettcannon** [comment] 2017-04-28 20:34
@csabella Probably https://cpython-devguide.readthedocs.io/documenting.html should mention it somehow.
