### ISSUE TITLE
Broken "Copyright" link at the footer of DevGuide

### ISSUE THREAD

**Issue by Mariatta** [python/devguide#652] opened 2021-01-14 16:41 UTC
At the bottom of the Devguide, there is a link to Copyright that points to https://devguide.python.org/copyright/ which doesn't exist.

It would be great to fix that. Not even sure where it should go. Should it just point to the license? https://github.com/python/devguide/blob/master/LICENSE

**Comment by cyberShaw** [comment] 2021-02-06 15:09
Can I work on this? I'm new to open source, and would love to contribute :D

**Comment by jablonskidev** [comment] 2021-03-07 19:22
@Mariatta I addressed this issue in the following PR in python-docs-theme: 
https://github.com/python/python-docs-theme/pull/67

Also, issues #652 and #653 for the devguide are duplicates of each other, so we'll be able to close two issues once this one is resolved.

**Comment by hugovk** [comment] 2022-01-27 11:12
Closing as a duplicate of https://github.com/python/devguide/issues/653.

**Closed by hugovk** 2022-01-27 11:12 UTC
Labels: duplicate
