### ISSUE TITLE
Add tips for effective online communication to devguide

### ISSUE THREAD

**Issue by brettcannon** [python/devguide#9] opened 2016-07-22 19:49 UTC
Originally from http://bugs.python.org/issue24689

**Comment by nilabja10201992** [comment] 2017-02-10 17:18
I'm a new contributor and I would like to help.

**Comment by willingc** [comment] 2017-02-10 18:34
Hi @nilabja10201992,

Welcome. Rereading the original issue, it looks as if there are two possible actions:

- [ ] [Section 12.1](https://cpython-devguide.readthedocs.io/communication.html#mailing-lists) Review mailing list descriptions and add any that are missing. Review the textbox and correct the formatting within the box.

- [ ] [Section 12.4](https://cpython-devguide.readthedocs.io/communication.html#standards-of-behaviour-in-these-communication-channels) Effective communication tips - A lot has improved since the initial opening of this issue on bugs.

**Comment by louisrawlins** [comment] 2017-02-11 01:17
Hi @willingc and @brettcannon.

Thanks a bunch for your help on the [core mentorship](https://www.python.org/dev/core-mentorship/) list.

I'd like to help with documentation. I'm new to Open-source, but comfortable with Git workflows (once we've established what they are).

@willingc, I could use most help finding documentation updates and discussing what needs doing. Please let me know how (or if) you're assigning tasks to be done from this issue, in particular.

I'm happy to get to work on [Section 12.1](https://cpython-devguide.readthedocs.io/communication.html#mailing-lists) and [Section 12.4](https://cpython-devguide.readthedocs.io/communication.html#standards-of-behaviour-in-these-communication-channels). 

For the [Section 12.4](https://cpython-devguide.readthedocs.io/communication.html#standards-of-behaviour-in-these-communication-channels), let me know what your gauge is for "done" and whether you think this part of the issue is closed. I'm using the thread with you and Enzio for inspiration. I found a quote I liked from Nick Coghlan where he says that 

> "putting openness, respect and kindness into practice on a public international mailing list that now mixes paid contributors with volunteers is a genuinely hard task that could likely benefit from a few pragmatic tips :)"

Thank you again for your help. I appreciate your support and guidance.

**Comment by louisrawlins** [comment] 2017-02-16 22:19
@willingc Wanted to share some thoughts on changed before I commit anything. I've made some changes to help clarify the common Python mailing lists here:

https://github.com/louisrawlins/devguide/wiki/https:--cpython-devguide.readthedocs.io-communication.html%23mailing-lists

Can you tell me what "Review the textbox and correct the formatting within the box." means? I'm happy to add any lists that should be there. I've only made clarifying updating, so far with a little reordering of topics for new readers.

@nilabja10201992 Sorry for munging your change. It'll get updated better when I commit -- I'm struggling to get the Github Wiki to render all of the reStructuredText properly.

**Comment by nilabja10201992** [comment] 2017-02-17 07:21
@louisrawlins  If you feel like to add more changes, it's fine, nothing to be sorry. I made changes which I felt appropriate if you feel more changes are necessary you can surely work on it.
Thank You!

**Comment by brettcannon** [comment] 2017-02-24 23:01
@louisrawlins the link you provided didn't seem to work and in the various wiki pages I couldn't find the word "textbox" so I don't know the context of the text you would like more info about.

**Comment by louisrawlins** [comment] 2017-02-24 23:28
Hi Brett. Shoot, sorry about that. I've updated my comment to clarify. My
question about "textbox" was intended for Carol, but if you have input,
please let me know.

**Comment by willingc** [comment] 2018-03-26 13:50
Closing as original issue submitter and devguide covers in several places.

**Closed by willingc** 2018-03-26 13:50 UTC
Labels: enhancement
